// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dogovetdxhmankfhpkgi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvZ292ZXRkeGhtYW5rZmhwa2dpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMDE2MDQsImV4cCI6MjA1OTY3NzYwNH0.ndj9Ho0dq0Zn-Y4T2WC7z8qVaWzEPP39ic47pJNB7DU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);